export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const AboutUs = () => {
    return (
        <div>
            AboutUs
            <p>abouts</p>
        </div>
    );
};

export default AboutUs;