

import dns from "node:dns/promises";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Poppins } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "Dragon News",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={` h-full antialiased`}
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
