export const metadata = {
  title: "Career",
  description: "Generated by create next app",
};

const CareerPage = () => {
    return (
        <div>
            CareerPage
        </div>
    );
};

export default CareerPage;